<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\zenith\zenith.csproj" />
    <ProjectReference Include="..\raknet\raknet.csproj" />
    <ProjectReference Include="..\..\libs\diagnostics\diagnostics.csproj" />
  </ItemGroup>

</Project>
