using System.Text;

namespace Zenith.ProtocolImport.Schema;

/// <summary>Writes the durable evidence for a schema bump; it does not edit packet sources.</summary>
internal static class UpgradeReportWriter
{
    public static void Write(
        string path, CacheManifest from, CacheManifest to, UpgradeSummary summary,
        SchemaCoverage coverage)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        var markdown = new StringBuilder();
        markdown.AppendLine($"# Bedrock protocol upgrade: {to.RequestedRef}");
        markdown.AppendLine();
        markdown.AppendLine("Generated by `protocol-import upgrade`. Review and commit this report with the protocol bump.");
        markdown.AppendLine();
        markdown.AppendLine("## Snapshots");
        markdown.AppendLine();
        markdown.AppendLine("| Role | Requested ref | Resolved SHA | Files |");
        markdown.AppendLine("|---|---|---|---:|");
        markdown.AppendLine($"| Source | `{from.RequestedRef}` | `{from.ResolvedSha}` | {from.Files.Count} |");
        markdown.AppendLine($"| Target | `{to.RequestedRef}` | `{to.ResolvedSha}` | {to.Files.Count} |");
        WriteList(markdown, "Changed packets", summary.ChangedPackets);
        WriteChanges(markdown, "GREEN — safe codegen candidates", summary.Green);
        WriteChanges(markdown, "YELLOW — suggested human review", summary.Yellow);
        WriteChanges(markdown, "RED — manual action required", summary.Red);
        WriteList(markdown, "Added packets", summary.AddedPackets);
        WriteList(markdown, "Removed packets", summary.RemovedPackets);
        WriteList(markdown, "Decisions", summary.RecommendedActions);
        WriteList(markdown, "Manual actions", summary.Red.Select(change =>
            $"Review `{change.Packet}`: {change.Description}"));
        WriteList(markdown, "Unsupported schema reasons", coverage.Unsupported.Select(item =>
            $"`{item.Packet}.{item.Field}` — {item.Reason}"));
        File.WriteAllText(path, markdown.ToString());
    }

    private static void WriteChanges(StringBuilder markdown, string heading, IEnumerable<SchemaChange> changes) =>
        WriteList(markdown, heading, changes.Select(change => $"`{change.Packet}` — {change.Description}"));

    private static void WriteList(StringBuilder markdown, string heading, IEnumerable<string> values)
    {
        markdown.AppendLine();
        markdown.AppendLine($"## {heading}");
        markdown.AppendLine();
        var items = values.ToList();
        if (items.Count == 0)
        {
            markdown.AppendLine("None.");
            return;
        }
        foreach (var item in items) markdown.AppendLine($"- {item}");
    }
}
