<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Zenith.Raknet</RootNamespace>
    <Namespace>Zenith.RakNet</Namespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="raknet.Tests" />
  </ItemGroup>

</Project>
