using System.Text;
using Zenith.PacketGenerator;
using Zenith.ProtocolImport.Schema;

namespace Zenith.ProtocolImport.Scaffolding;

/// <summary>Produces a narrow partial-class addition for a scalar GREEN field; never rewrites a packet.</summary>
internal static class GreenAttributePatchScaffolder
{
    public static bool TryScaffold(PacketSchema packet, FieldSchema field, out string source, out string reason)
    {
        source = "";
        reason = "";
        if (field.Construct != SchemaConstruct.Scalar || field.RepeatPrefix is not null || field.IsConstantLiteral || field.IsComplexType)
        {
            reason = "only scalar, non-constant fields are safe for attribute automation";
            return false;
        }
        var emission = KnownTypeMap.Resolve(field.Type);
        if (emission.Kind == WireEmissionKind.Unknown)
        {
            reason = $"type '{field.Type}' has no proven generic wire mapping";
            return false;
        }
        var attribute = emission.Kind switch
        {
            WireEmissionKind.Fixed when emission.Endianess is not null => $"[Wire(BinaryStream.Endianess.{emission.Endianess})]",
            WireEmissionKind.Fixed => "[Wire]",
            WireEmissionKind.Var => "[WireVar]",
            WireEmissionKind.String => "[WireString]",
            WireEmissionKind.Uuid => "[WireUuid]",
            WireEmissionKind.ByteArray => "[WireByteArray]",
            _ => throw new InvalidOperationException()
        };
        var name = PropertyNamer.ToPascalCase(field.Name);
        var type = field.Optional ? emission.ClrType + "?" : emission.ClrType;
        var initializer = field.Optional ? "" : emission.ClrType switch { "string" => " = \"\";", "byte[]" => " = [];", _ => "" };
        var sb = new StringBuilder();
        sb.AppendLine("using Zenith.Packets.Generation;");
        sb.AppendLine("using Zenith.Raknet.Stream;");
        sb.AppendLine();
        sb.AppendLine("namespace Zenith.Packets;");
        sb.AppendLine();
        sb.AppendLine($"// Generated by protocol-import for a GREEN schema addition in {packet.Name}.{field.Name}.");
        sb.AppendLine($"partial class {packet.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"    {attribute}");
        if (field.Optional) sb.AppendLine("    [WireOptional]");
        sb.AppendLine($"    public {type} {name} {{ get; set; }}{initializer}");
        sb.AppendLine("}");
        source = sb.ToString();
        return true;
    }
}
