namespace zenith.Network.Protocol;

enum ProtocolInfo : int
{
    LOGIN_PACKET = 0x01,
    PLAY_STATUS_PACKET = 0x02,
    RESOURCE_PACKS_INFO_PACKET = 0x06,
    RESOURCE_PACK_STACK_PACKET = 0x07,
    RESOURCE_PACK_CLIENT_RESPONSE_PACKET = 0x08,
    START_GAME_PACKET = 0x0b,
    REQUEST_NETWORK_SETTINGS_PACKET = 0xc1,
    NETWORK_SETTINGS_PACKET = 0x8f
}