<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\raknet\raknet.csproj" />
    <ProjectReference Include="..\..\libs\nbt\nbt.csproj" />
    <ProjectReference Include="..\..\libs\leveldb\leveldb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="data\block_palette.nbt">
      <LogicalName>block_palette.nbt</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="data\creative_items.json">
      <LogicalName>creative_items.json</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="data\item_palette.json">
      <LogicalName>item_palette.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Version>0.0.2-alpha</Version>
    <InformationalVersion>0.0.2-alpha</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="zenith.Tests" />
    <InternalsVisibleTo Include="zenith.Benchmarks" />
  </ItemGroup>

</Project>
